# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e08b70ead75974804c15c8009bc03ef6b59c9cc040a2436c9dcefba8618c79a003610f29ecf411b1384c13d8050095581bf35ca2d7978a09eb775fd7f567333

test:
  secret_key_base: 8722846084b3bd80d747ea12850a26a85cf82c809bd506bf3922aea08307bff7489ded7792beebe40158a649032864b05e0151e2b30e1a035593975decf8e697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
